---
- name: Install python
  ansible.builtin.include_role:
    name: "{{ item }}"
  loop:
    - ensure-python
    - ensure-pip

- name: Install mypy
  ansible.builtin.pip:
    name: "mypy=={{ mypy_version }}"
    virtualenv: "{{ python_venv_dir }}"
    virtualenv_command: "python3 -m venv"

- name: Install repo requirements
  ansible.builtin.pip:
    requirements: "requirements.txt"
    virtualenv: "{{ python_venv_dir }}"
    chdir: "{{ zuul_work_dir }}"

- name: Run mypy
  ansible.builtin.command:
    cmd: "{{ python_venv_dir }}/bin/python3 -m mypy --ignore-missing-imports --install-types --non-interactive ."
    chdir: "{{ zuul_work_dir }}"
  changed_when: false
