---
- job:
    name: ansible-collection-ensure-readme
    description: ansible-collection-ensure-readme job provided by OSISM
    run: playbooks/ansible-collection-ensure-readme/run.yaml

- job:
    name: ansible-lint
    description: ansible-lint job provided by OSISM
    run: playbooks/ansible-lint/run.yaml

- job:
    name: ansible-molecule
    description: ansible-molecule job provided by OSISM
    run: playbooks/ansible-molecule/run.yaml

- job:
    name: check-shell-syntax
    description: check-shell-syntax job provided by OSISM
    run: playbooks/check-shell-syntax/run.yaml

- job:
    name: dcolicense
    description: dcolicense job provided by OSISM
    run: playbooks/dcolicense/run.yaml

- job:
    name: devstack
    description: devstack job provided by OSISM
    run: playbooks/devstack/run.yaml

- job:
    name: flake8
    description: flake8 job provided by OSISM
    run: playbooks/flake8/run.yaml

- job:
    name: hadolint
    description: hadolint job provided by OSISM
    run: playbooks/hadolint/run.yaml

- job:
    name: mypy
    description: mypy job provided by OSISM
    run: playbooks/mypy/run.yaml

- job:
    name: publish-pypi-package
    description: publish-pypi-package job provided by OSISM
    pre-run: playbooks/publish-pypi-package/pre-run.yaml
    run: playbooks/publish-pypi-package/run.yaml
    post-run: playbooks/publish-pypi-package/post-run.yaml

- job:
    name: python-black
    description: python-black job provided by OSISM
    run: playbooks/python-black/run.yml

- job:
    name: yamllint
    description: yamllint job provided by OSISM
    run: playbooks/yamllint/run.yaml

- project:
    merge-mode: squash-merge
    check:
      jobs:
        - ansible-lint
        - flake8
        - python-black
        - yamllint
    gate:
      jobs:
        - ansible-lint
        - flake8
        - python-black
        - yamllint
