---
- job: 
    name: ansible-lint
    run: playbooks/ansible-lint/run.yaml

- job:
    name: flake8
    run: playbooks/flake8/run.yaml

- job:
    name: yamllint
    run: playbooks/yamllint/run.yaml
