---
- name: Developer Certificate of Origin (DCO) license check
  ansible.builtin.shell:
    cmd: |
      set -eo pipefail
      result=0
      for commit in $(git cherry -v origin/{{ zuul.branch }} HEAD | cut -d " " -f2)
      do
        if ! git show -s $commit | grep -q "Signed-off-by:"; then
          echo "---"
          git show -s $commit
          echo "---"
          echo "does not have a Signed-off-by header"
          result=1
        fi
      done
      exit $result      
    chdir: "{{ zuul_work_dir }}"
    executable: /bin/bash
  register: dcolicense_status
  failed_when: dcolicense_status.rc > 1
  changed_when: false

- name: License check failed
  ansible.builtin.fail:
    msg: "{{ dcolicense_failure }}"
  when: dcolicense_status.rc != 0
