---
- name: Install Python
  ansible.builtin.include_role:
    name: "{{ item }}"
  loop:
    - ensure-python
    - ensure-pip

- name: Install pip module flake8
  ansible.builtin.pip:
    name: flake8
    state: latest
    virtualenv: "{{ python_venv_dir }}"
    virtualenv_command: "python3 -m venv"
    # noqa package-latest

- name: Find all .py files
  ansible.builtin.find:
    paths: "{{ zuul_work_dir }}"
    pattern: "*.py"
    excludes: "{{ flake8_excludes }}"
    recurse: true
  register: flake8_py_files

- name: Run flake8
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      set -e
      {{ python_venv_dir }}/bin/python3 -m flake8 {{ file | relpath(zuul_work_dir) }} 2>&1 | tee -a flake8.txt
    chdir: "{{ zuul_work_dir }}"
    executable: /bin/bash
  loop: "{{ flake8_py_files.files | map(attribute='path') | list }}"
  loop_control:
    loop_var: file
  changed_when: false
