---
- name: Force update of package cache
  become: true
  ansible.builtin.apt:
    update_cache: true

- name: Set python_version
  ansible.builtin.set_fact:
    python_version: "3.11"
  when: ansible_distribution_release == "jammy"

- name: Install python
  ansible.builtin.include_role:
    name: ensure-python

- name: Install pip
  ansible.builtin.include_role:
    name: ensure-pip
  when: ansible_distribution_release != "jammy"

- name: Install Ansible {{ ansible_molecule_ansible_version }}
  ansible.builtin.pip:
    name: "ansible=={{ ansible_molecule_ansible_version }}"
    virtualenv: "{{ ansible_molecule_venv }}"
    virtualenv_command: python3 -m venv
    state: present
  when: ansible_distribution_release != "jammy"

- name: Install Ansible {{ ansible_molecule_ansible_version }}
  ansible.builtin.pip:
    name: "ansible=={{ ansible_molecule_ansible_version }}"
    virtualenv: "{{ ansible_molecule_venv }}"
    virtualenv_command: python3.11 -m venv
    state: present
  when: ansible_distribution_release == "jammy"
