---
# tasks file for ansible_molecule
- name: Include OS specific vars
  ansible.builtin.include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_release | default(ansible_distribution_version) }}.yml"

- name: Update package cache
  become: true
  ansible.builtin.apt:
    update_cache: true
  when: ansible_distribution == "Ubuntu"

- name: Install Python
  ansible.builtin.include_role:
    name: "{{ item }}"
  loop:
    - ensure-python
    - ensure-pip

- name: Install Ansible {{ ansible_molecule_ansible_version }}
  ansible.builtin.pip:
    name: "ansible=={{ ansible_molecule_ansible_version }}"
    virtualenv: "{{ ansible_molecule_venv }}"
    virtualenv_command: python3 -m venv
    state: present

- name: Install requests
  ansible.builtin.pip:
    virtualenv: "{{ ansible_molecule_venv }}"
    name: requests
    chdir: "{{ zuul_work_dir }}"

- name: Install requirements
  ansible.builtin.pip:
    virtualenv: "{{ ansible_molecule_venv }}"
    requirements: molecule/requirements.txt
    chdir: "{{ zuul_work_dir }}"

- name: Run molecule dependency action with scenario delegated
  ansible.builtin.shell:
    cmd: |
      set -e
      . {{ ansible_molecule_venv }}/bin/activate
      python -m molecule --debug -v dependency -s delegated
    chdir: "{{ zuul_work_dir }}"
    executable: /bin/bash
  environment:
    ANSIBLE_ROLE: "{{ ansible_role }}"
    ANSIBLE_PYTHON_INTERPRETER: "{{ ansible_molecule_venv }}/bin/python"
  changed_when: true
  when: ansible_molecule_dependency | default(true) | bool

- name: Run molecule create action with scenario delegated
  ansible.builtin.shell:
    cmd: |
      set -e
      . {{ ansible_molecule_venv }}/bin/activate
      python -m molecule --debug -v create -s delegated
    chdir: "{{ zuul_work_dir }}"
    executable: /bin/bash
  environment:
    ANSIBLE_ROLE: "{{ ansible_role }}"
    ANSIBLE_PYTHON_INTERPRETER: "{{ ansible_molecule_venv }}/bin/python"
  changed_when: true
  when: ansible_molecule_create | default(false) | bool

- name: Run molecule prepare action with scenario delegated
  ansible.builtin.shell:
    cmd: |
      set -e
      . {{ ansible_molecule_venv }}/bin/activate
      python -m molecule --debug -v prepare -s delegated
    chdir: "{{ zuul_work_dir }}"
    executable: /bin/bash
  environment:
    ANSIBLE_ROLE: "{{ ansible_role }}"
    ANSIBLE_PYTHON_INTERPRETER: "{{ ansible_molecule_venv }}/bin/python"
  changed_when: true
  when: ansible_molecule_prepare | default(true) | bool

- name: Reset connection
  ansible.builtin.meta: reset_connection

- name: Run molecule converge action with scenario delegated
  ansible.builtin.shell:
    cmd: |
      set -e
      . {{ ansible_molecule_venv }}/bin/activate
      python -m molecule --debug -v converge -s delegated
    chdir: "{{ zuul_work_dir }}"
    executable: /bin/bash
  environment:
    ANSIBLE_ROLE: "{{ ansible_role }}"
    ANSIBLE_PYTHON_INTERPRETER: "{{ ansible_molecule_venv }}/bin/python"
  changed_when: true
  when: ansible_molecule_converge | default(true) | bool

- name: Run molecule verify action with scenario delegated
  ansible.builtin.shell:
    cmd: |
      set -e
      . {{ ansible_molecule_venv }}/bin/activate
      python -m molecule --debug -v verify -s delegated
    chdir: "{{ zuul_work_dir }}"
    executable: /bin/bash
  environment:
    ANSIBLE_ROLE: "{{ ansible_role }}"
    ANSIBLE_PYTHON_INTERPRETER: "{{ ansible_molecule_venv }}/bin/python"
  changed_when: true
  when: ansible_molecule_verify | default(true) | bool

- name: Run molecule destroy action with scenario delegated
  ansible.builtin.shell:
    cmd: |
      set -e
      . {{ ansible_molecule_venv }}/bin/activate
      python -m molecule --debug -v destroy -s delegated
    chdir: "{{ zuul_work_dir }}"
    executable: /bin/bash
  environment:
    ANSIBLE_ROLE: "{{ ansible_role }}"
    ANSIBLE_PYTHON_INTERPRETER: "{{ ansible_molecule_venv }}/bin/python"
  changed_when: true
  when: ansible_molecule_destroy | default(false) | bool
