---
- name: Pull ansible-lint image
  ansible.builtin.command:
    cmd: "podman pull osism.harbor.regio.digital/osism/ansible-lint:latest"
  changed_when: false

- name: Run ansible-lint
  ansible.builtin.command:
    cmd: "podman run --volume ./{{ zuul.project.src_dir }}:/zuul:rw osism.harbor.regio.digital/osism/ansible-lint:latest"
  register: result
  failed_when: "'0 failure(s)' not in result.stdout"
  changed_when: false
