---
- name: Install python
  ansible.builtin.include_role:
    name: "{{ item }}"
  loop:
    - ensure-python
    - ensure-pip

- name: Install yamllint
  ansible.builtin.pip:
    name: "yamllint=={{ yamllint_version }}"
    virtualenv: "{{ python_venv_dir }}"
    virtualenv_command: "python3 -m venv"

- name: Run yamllint
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      set -e
      {{ python_venv_dir }}/bin/python3 -m yamllint . 2>&1 | tee -a yamllint.txt
    chdir: "{{ zuul_work_dir }}"
    executable: /bin/bash
  changed_when: false
