---
- name: Install python
  ansible.builtin.include_role:
    name: "{{ item }}"
  loop:
    - ensure-python
    - ensure-pip

- name: Install yamllint
  ansible.builtin.pip:
    name: yamllint
    executable: pip3

- name: Run yamllint
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      set -e
      python3 -m yamllint . 2>&1 | tee -a yamllint.txt
    chdir: "{{ zuul.project.src_dir }}"
    executable: /bin/bash
  changed_when: false
